service: ${file(./package.json):name}
frameworkVersion: "3"
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-prune-plugin
package:
  individually: true
custom:
  usersTableName: ${sls:stage}.${self:service}.users
  cognitoClientName: my-cognito-client # defined on creation in AWS Console > Cognito > Userpools
  serverless-offline:
    allowCache: true # Prevemt serverless-offline from eating all of your memory
    useChildProcesses: true
    # httpsProtocol: "dev-certs"
    # httpPort: 4000
    # stageVariables:
    #   foo: "bar"
  prune:
    automatic: true
    number: 3
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node16
    platform: node
    concurrency: 10
provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs16.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    # JWT_EXPIRY: ${ssm:/aws/reference/secretsmanager/dev/user-api/jwt-expiry}
    JWT_EXPIRY: "2d"
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    STAGE: ${sls:stage}
    COGNITO_POOL_ID: { Ref: CogniteUserPool }
    COGNITO_CLIENT_ID: { Ref: CognitoUserClient }
    USERS_TABLE_NAME: ${self:custom.usersTableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminGetUser
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminAddUserToGroup
            - cognito-idp:ListUsers
            - cognito-idp:CreateGroup
            - cognito-idp:GetGroup
            - cognito-idp:GetUser
          Resource: "*"
          # Resource:
          #   - Fn::GetAtt: [CogniteUserPool, Arn]
          #   - Fn::GetAtt: [CognitoUserClient, Arn]
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:DescribeStream
            - dynamodb:ListStreams
            - dynamodb:GetRecords
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UserTable, Arn]
            # - !Sub "${UserTable.Arn}"
        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource:
            # - !Sub "${UserTable.Arn}"
            - !Sub "${UserTable.Arn}/index/*"
            # - !Sub "${UserTable.Arn}/index/EmailIndex"
functions:
  getUserById:
    handler: src/handlers/user/by-id.handler
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
  getUserByName:
    handler: src/handlers/user/by-name.handler
    events:
      - http:
          path: user/name/{name}
          method: get
          cors: true
  getUserByEmail:
    handler: src/handlers/user/by-email.handler
    events:
      - http:
          path: user/email/{email}
          method: get
          cors: true
  getUserByHandle:
    handler: src/handlers/user/by-handle.handler
    events:
      - http:
          path: user/handle/{handle}
          method: get
          cors: true
  register:
    handler: src/handlers/user/register.handler
    events:
      - http:
          path: user
          method: post
          cors: true
  confirmAccount:
    handler: src/handlers/user/activate.handler
    events:
      - http:
          path: user/activate/{activationCode}
          method: get
          cors: true
  updateUserStatus:
    handler: src/handlers/user/update-status.handler
    events:
      - http:
          path: user/{id}/status/{status}
          method: patch
          cors: true
  login:
    handler: src/handlers/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true
  verifyToken:
    handler: src/handlers/auth/verify-token.handler
    events:
      - http:
          path: auth/token/{tokenType}/verify/{token}
          method: get
          cors: true

  # TODO
  # addBadge:
  #   handler: src/handlers/add-badge.handler
  #   events:
  #     - http:
  #         path: user/{id}/badge
  #         method: patch
  #         cors: true
  # TODO
  # removeBadge:
  #   handler: src/handlers/remove-badge.handler
  #   events:
  #     - http:
  #         path: user/{id}/badge
  #         method: delete
  #         cors: true
  # TODO Usecase: Post account activation, password reset in progress, banned etc.
  # updateStatus:
  #   handler: src/handlers/status.handler
  #   events:
  #     - http:
  #         path: user/{id}/status
  #         method: patch
  #         cors: true
resources:
  Resources:
    CogniteUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: serverless-auth-pool
        EmailVerificationSubject: "Your verification Code"
        EmailVerificationMessage: "Use this code to confirm your sign up {####}"
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        Schema:
          - Name: email
            Required: true
            Mutable: true
          - Name: name
            Required: true
            Mutable: false
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: False
            RequireSymbols: False
            RequireUppercase: False
    CognitoUserPoolGroupUser:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: "Users"
        GroupName: "USER"
        UserPoolId: { Ref: CogniteUserPool }
    CognitoUserPoolGroupModerator:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: "Moderators"
        GroupName: "MODERATOR"
        UserPoolId: { Ref: CogniteUserPool }
    CognitoUserPoolGroupAdmin:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: "Admins"
        GroupName: "ADMIN"
        UserPoolId: { Ref: CogniteUserPool }
    CognitoUserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.cognitoClientName}
        GenerateSecret: false
        UserPoolId: { Ref: CogniteUserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: handle
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: activationCode
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: NameIndex
            KeySchema:
              - AttributeName: name
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: HandleIndex
            KeySchema:
              - AttributeName: handle
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: ActivationCodeIndex
            KeySchema:
              - AttributeName: activationCode
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        BillingMode: PAY_PER_REQUEST
    # MyApi:
    #   Type: AWS::Serverless::Api
    #   Properties:
    #     StageName: dev
    #     Cors: "'*'"
    #     Auth:
    #       DefaultAuthorizer: MyCognitoAuthorizer
    #       Authorizers:
    #         MyCognitoAuthorizer:
    #           UserPoolArn: !GetAtt CogniteUserPool.Arn
